travis:
  secure:
    BINSTAR_TOKEN: s4uLro7FzzfH4Wj7WqGxQjMb16xAVxbXtXNgSIj44T0KBhUfqZMFfC2Q3PJih1Z9elzCFt7OUj1fX3siQ3MqvL/dAvrua9SvZiS2avkUWPZqAmG3DEzD3mW5jJtfAn72c5bHJsAwe1kZDRyovD4YUx4z3NIxzZU2JPf6ABmF6QhIrpGZuc0/BRJXs/jv6TiXUn7AsEVjgGlYLkQ14F0f0t5GA8OBKlxIdKiM92x8gd2KdWL2DAyLM53uO2PPrl9Q5MXcyrWjArUJMhah2dyYgy9Dw+AJC5OoG/rkv7JHFE6FZBHX6mvjo2lXS6wrruK94yfC3K3UiWwToOeFKFhlv7g4ajk9bUONTThiqh5jPP1J3TfBiuLwMy0psp+wb44iKI91McZUWxLmEEr9LA6jR6Vhjcm+FxEs0BGkZlGo4riF9EycpnKN8EmxIg32AU15qaTdeOLcVFL/Y59DYFlibPbFch+Ahx+bK7C3whdDM6HAnPCZRxoef+IOCN//ZfMBVb/0k4ppkzGxgGlutUywLkbE+zUfp8Ar1VBtWb8gIlkgCKjJbPN0XQu2h3v0jwyUmybn3njGejijkfZi9PMGDqBqVww0qdHhtObBG9/B4+7zc6qnwpAZ+/FVx/eCwHUlbsGtCFi02SmlYooRaJJZx+VA+LeDJyZyt0dLdxH5SVw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
